apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordinance
  namespace: sima
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordinance-rest
  template:
    metadata:
      labels:
        app: ordinance-rest
    spec:
      containers:
      - name: ordinance-rest
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/ordinance:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-gunicorn-server", "--workers", "10"]
        ports:
        - name: rest
          containerPort: 5000
        envFrom:
          - secretRef:
              name: ordinance-secret
          - configMapRef:
              name: ordinance-conf
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
      - name: ordinance-kafka
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/ordinance:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-consumer"]
        envFrom:
          - secretRef:
              name: ordinance-secret
          - configMapRef:
              name: ordinance-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"

      imagePullSecrets:
          - name: regcred
